Update applanga-pull.yml

diff --git a/.github/workflows/applanga-pull.yml b/.github/workflows/applanga-pull.yml
--- a/.github/workflows/applanga-pull.yml
+++ b/.github/workflows/applanga-pull.yml
@@ -68,19 +68,19 @@ jobs:
           title: ${{ github.event.inputs.pr_title }}
           body: Pulled in new translations from Applanga portal
           path: checkout
-      - name: Notify workflow success
-        if: success()
-        run: |-
-          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ github.event.inputs.mobileAppId }}" \
-            -H "Content-Type: application/json" \
-            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
-            -d '{
-              "branchId": "${{ github.event.inputs.branchId }}",
-              "workflowType": "pull",
-              "status": "success"
-            }' || echo "Failed to notify workflow success"
+      # - name: Notify workflow success
+      #   if: success()
+      #   run: |-
+      #     curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ github.event.inputs.mobileAppId }}" \
+      #       -H "Content-Type: application/json" \
+      #       -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
+      #       -d '{
+      #         "branchId": "${{ github.event.inputs.branchId }}",
+      #         "workflowType": "pull",
+      #         "status": "success"
+      #       }' || echo "Failed to notify workflow success"
       - name: Notify workflow failure
-        if: failure()
+        # if: failure()
         run: |-
           curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ github.event.inputs.mobileAppId }}" \
             -H "Content-Type: application/json" \
